---
# tasks file for main

- name: Download Google Chrome
  win_get_url:
    url: https://dl.google.com/tag/s/appguid%3D%7B8A69D345-D564-463C-AFF1-A69D9E530F96%7D%26iid%3D%7B24F3351A-A4AF-042A-4DA6-AEE56456DDA4%7D%26lang%3Den%26browser%3D4%26usagestats%3D1%26appname%3DGoogle%2520Chrome%26needsadmin%3Dprefers%26ap%3Dx64-stable-statsdef_1%26installdataindex%3Ddefaultbrowser/update2/installers/ChromeStandaloneSetup64.exe
    dest: '%TEMP%\chrome64.exe'

- name: Install Google Chrome
  win_command: chrome64.exe /silent /install
  args:
    chdir: '%TEMP%'